// 90 RSS feeds from Hacker News Popularity Contest 2025
// Curated by Andrej Karpathy

export const RSS_FEEDS = [
  { name: "simonwillison.net", xmlUrl: "https://simonwillison.net/atom/everything/", htmlUrl: "https://simonwillison.net" },
  { name: "jeffgeerling.com", xmlUrl: "https://www.jeffgeerling.com/blog.xml", htmlUrl: "https://jeffgeerling.com" },
  { name: "seangoedecke.com", xmlUrl: "https://www.seangoedecke.com/rss.xml", htmlUrl: "https://seangoedecke.com" },
  { name: "krebsonsecurity.com", xmlUrl: "https://krebsonsecurity.com/feed/", htmlUrl: "https://krebsonsecurity.com" },
  { name: "daringfireball.net", xmlUrl: "https://daringfireball.net/feeds/main", htmlUrl: "https://daringfireball.net" },
  { name: "ericmigi.com", xmlUrl: "https://ericmigi.com/rss.xml", htmlUrl: "https://ericmigi.com" },
  { name: "antirez.com", xmlUrl: "http://antirez.com/rss", htmlUrl: "http://antirez.com" },
  { name: "idiallo.com", xmlUrl: "https://idiallo.com/feed.rss", htmlUrl: "https://idiallo.com" },
  { name: "maurycyz.com", xmlUrl: "https://maurycyz.com/index.xml", htmlUrl: "https://maurycyz.com" },
  { name: "pluralistic.net", xmlUrl: "https://pluralistic.net/feed/", htmlUrl: "https://pluralistic.net" },
  { name: "shkspr.mobi", xmlUrl: "https://shkspr.mobi/blog/feed/", htmlUrl: "https://shkspr.mobi" },
  { name: "lcamtuf.substack.com", xmlUrl: "https://lcamtuf.substack.com/feed", htmlUrl: "https://lcamtuf.substack.com" },
  { name: "mitchellh.com", xmlUrl: "https://mitchellh.com/feed.xml", htmlUrl: "https://mitchellh.com" },
  { name: "dynomight.net", xmlUrl: "https://dynomight.net/feed.xml", htmlUrl: "https://dynomight.net" },
  { name: "utcc.utoronto.ca/~cks", xmlUrl: "https://utcc.utoronto.ca/~cks/space/blog/?atom", htmlUrl: "https://utcc.utoronto.ca/~cks" },
  { name: "xeiaso.net", xmlUrl: "https://xeiaso.net/blog.rss", htmlUrl: "https://xeiaso.net" },
  { name: "devblogs.microsoft.com/oldnewthing", xmlUrl: "https://devblogs.microsoft.com/oldnewthing/feed", htmlUrl: "https://devblogs.microsoft.com/oldnewthing" },
  { name: "righto.com", xmlUrl: "https://www.righto.com/feeds/posts/default", htmlUrl: "https://righto.com" },
  { name: "lucumr.pocoo.org", xmlUrl: "https://lucumr.pocoo.org/feed.atom", htmlUrl: "https://lucumr.pocoo.org" },
  { name: "skyfall.dev", xmlUrl: "https://skyfall.dev/rss.xml", htmlUrl: "https://skyfall.dev" },
  { name: "garymarcus.substack.com", xmlUrl: "https://garymarcus.substack.com/feed", htmlUrl: "https://garymarcus.substack.com" },
  { name: "rachelbythebay.com", xmlUrl: "https://rachelbythebay.com/w/atom.xml", htmlUrl: "https://rachelbythebay.com" },
  { name: "overreacted.io", xmlUrl: "https://overreacted.io/rss.xml", htmlUrl: "https://overreacted.io" },
  { name: "timsh.org", xmlUrl: "https://timsh.org/rss/", htmlUrl: "https://timsh.org" },
  { name: "johndcook.com", xmlUrl: "https://www.johndcook.com/blog/feed/", htmlUrl: "https://johndcook.com" },
  { name: "gilesthomas.com", xmlUrl: "https://gilesthomas.com/feed/rss.xml", htmlUrl: "https://gilesthomas.com" },
  { name: "matklad.github.io", xmlUrl: "https://matklad.github.io/feed.xml", htmlUrl: "https://matklad.github.io" },
  { name: "derekthompson.org", xmlUrl: "https://www.theatlantic.com/feed/author/derek-thompson/", htmlUrl: "https://derekthompson.org" },
  { name: "evanhahn.com", xmlUrl: "https://evanhahn.com/feed.xml", htmlUrl: "https://evanhahn.com" },
  { name: "terriblesoftware.org", xmlUrl: "https://terriblesoftware.org/feed/", htmlUrl: "https://terriblesoftware.org" },
  { name: "rakhim.exotext.com", xmlUrl: "https://rakhim.exotext.com/rss.xml", htmlUrl: "https://rakhim.exotext.com" },
  { name: "joanwestenberg.com", xmlUrl: "https://joanwestenberg.com/rss", htmlUrl: "https://joanwestenberg.com" },
  { name: "xania.org", xmlUrl: "https://xania.org/feed", htmlUrl: "https://xania.org" },
  { name: "micahflee.com", xmlUrl: "https://micahflee.com/feed/", htmlUrl: "https://micahflee.com" },
  { name: "nesbitt.io", xmlUrl: "https://nesbitt.io/feed.xml", htmlUrl: "https://nesbitt.io" },
  { name: "construction-physics.com", xmlUrl: "https://www.construction-physics.com/feed", htmlUrl: "https://construction-physics.com" },
  { name: "tedium.co", xmlUrl: "https://feed.tedium.co/", htmlUrl: "https://tedium.co" },
  { name: "susam.net", xmlUrl: "https://susam.net/feed.xml", htmlUrl: "https://susam.net" },
  { name: "entropicthoughts.com", xmlUrl: "https://entropicthoughts.com/feed.xml", htmlUrl: "https://entropicthoughts.com" },
  { name: "buttondown.com/hillelwayne", xmlUrl: "https://buttondown.com/hillelwayne/rss", htmlUrl: "https://buttondown.com/hillelwayne" },
  { name: "dwarkesh.com", xmlUrl: "https://www.dwarkeshpatel.com/feed", htmlUrl: "https://dwarkesh.com" },
  { name: "borretti.me", xmlUrl: "https://borretti.me/feed.xml", htmlUrl: "https://borretti.me" },
  { name: "wheresyoured.at", xmlUrl: "https://www.wheresyoured.at/rss/", htmlUrl: "https://wheresyoured.at" },
  { name: "jayd.ml", xmlUrl: "https://jayd.ml/feed.xml", htmlUrl: "https://jayd.ml" },
  { name: "minimaxir.com", xmlUrl: "https://minimaxir.com/index.xml", htmlUrl: "https://minimaxir.com" },
  { name: "geohot.github.io", xmlUrl: "https://geohot.github.io/blog/feed.xml", htmlUrl: "https://geohot.github.io" },
  { name: "paulgraham.com", xmlUrl: "http://www.aaronsw.com/2002/feeds/pgessays.rss", htmlUrl: "https://paulgraham.com" },
  { name: "filfre.net", xmlUrl: "https://www.filfre.net/feed/", htmlUrl: "https://filfre.net" },
  { name: "blog.jim-nielsen.com", xmlUrl: "https://blog.jim-nielsen.com/feed.xml", htmlUrl: "https://blog.jim-nielsen.com" },
  { name: "dfarq.homeip.net", xmlUrl: "https://dfarq.homeip.net/feed/", htmlUrl: "https://dfarq.homeip.net" },
  { name: "jyn.dev", xmlUrl: "https://jyn.dev/atom.xml", htmlUrl: "https://jyn.dev" },
  { name: "geoffreylitt.com", xmlUrl: "https://www.geoffreylitt.com/feed.xml", htmlUrl: "https://geoffreylitt.com" },
  { name: "downtowndougbrown.com", xmlUrl: "https://www.downtowndougbrown.com/feed/", htmlUrl: "https://downtowndougbrown.com" },
  { name: "brutecat.com", xmlUrl: "https://brutecat.com/rss.xml", htmlUrl: "https://brutecat.com" },
  { name: "eli.thegreenplace.net", xmlUrl: "https://eli.thegreenplace.net/feeds/all.atom.xml", htmlUrl: "https://eli.thegreenplace.net" },
  { name: "abortretry.fail", xmlUrl: "https://www.abortretry.fail/feed", htmlUrl: "https://abortretry.fail" },
  { name: "fabiensanglard.net", xmlUrl: "https://fabiensanglard.net/rss.xml", htmlUrl: "https://fabiensanglard.net" },
  { name: "pthorpe92.github.io", xmlUrl: "https://pthorpe92.github.io/feed.xml", htmlUrl: "https://pthorpe92.github.io" },
  { name: "jacobian.org", xmlUrl: "https://jacobian.org/feed/", htmlUrl: "https://jacobian.org" },
  { name: "tenderlovemaking.com", xmlUrl: "https://tenderlovemaking.com/feed/", htmlUrl: "https://tenderlovemaking.com" },
  { name: "nicholas.carlini.com", xmlUrl: "https://nicholas.carlini.com/writing/feed.xml", htmlUrl: "https://nicholas.carlini.com" },
  { name: "nolanlawson.com", xmlUrl: "https://nolanlawson.com/feed/", htmlUrl: "https://nolanlawson.com" },
  { name: "steveblank.com", xmlUrl: "https://steveblank.com/feed/", htmlUrl: "https://steveblank.com" },
  { name: "troyhunt.com", xmlUrl: "https://feeds.feedburner.com/TroyHunt", htmlUrl: "https://troyhunt.com" },
  { name: "iquilezles.org", xmlUrl: "https://www.iquilezles.org/blog/index.xml", htmlUrl: "https://iquilezles.org" },
  { name: "mcmillen.dev", xmlUrl: "https://www.mcmillen.dev/rss.xml", htmlUrl: "https://mcmillen.dev" },
  { name: "expr-lang.org", xmlUrl: "https://expr-lang.org/blog/rss.xml", htmlUrl: "https://expr-lang.org" },
  { name: "schneier.com", xmlUrl: "https://www.schneier.com/blog/atom.xml", htmlUrl: "https://schneier.com" },
  { name: "thezvi.wordpress.com", xmlUrl: "https://thezvi.wordpress.com/feed/", htmlUrl: "https://thezvi.wordpress.com" },
  { name: "lemire.me", xmlUrl: "https://lemire.me/blog/feed/", htmlUrl: "https://lemire.me" },
  { name: "mikegazzaruso.substack.com", xmlUrl: "https://mikegazzaruso.substack.com/feed", htmlUrl: "https://mikegazzaruso.substack.com" },
  { name: "benhoyt.com", xmlUrl: "https://benhoyt.com/writings/rss.xml", htmlUrl: "https://benhoyt.com" },
  { name: "macwright.com", xmlUrl: "https://macwright.com/rss.xml", htmlUrl: "https://macwright.com" },
  { name: "adamchala.com", xmlUrl: "https://adamchala.com/rss.xml", htmlUrl: "https://adamchala.com" },
  { name: "gavinhoward.com", xmlUrl: "https://gavinhoward.com/feed/", htmlUrl: "https://gavinhoward.com" },
  { name: "emersion.fr", xmlUrl: "https://emersion.fr/blog/rss.xml", htmlUrl: "https://emersion.fr" },
  { name: "holub.com", xmlUrl: "https://holub.com/feed/", htmlUrl: "https://holub.com" },
  { name: "reasonabledeviations.com", xmlUrl: "https://reasonabledeviations.com/rss/", htmlUrl: "https://reasonabledeviations.com" },
  { name: "tarski.com", xmlUrl: "https://www.tarski.com/feed/", htmlUrl: "https://tarski.com" },
  { name: "thecoder08.github.io", xmlUrl: "https://thecoder08.github.io/rss.xml", htmlUrl: "https://thecoder08.github.io" },
  { name: "evanjconrad.com", xmlUrl: "https://www.evanjconrad.com/feed", htmlUrl: "https://evanjconrad.com" },
  { name: "satyamk.com", xmlUrl: "https://satyamk.com/posts/index.xml", htmlUrl: "https://satyamk.com" },
  { name: "mattambrogi.com", xmlUrl: "https://mattambrogi.com/feed", htmlUrl: "https://mattambrogi.com" },
  { name: "ptsjs.com", xmlUrl: "https://ptsjs.com/guide/rss", htmlUrl: "https://ptsjs.com" },
  { name: "matt-rickard.com", xmlUrl: "https://matt-rickard.com/rss.xml", htmlUrl: "https://matt-rickard.com" },
  { name: "sandyuraz.com", xmlUrl: "https://sandyuraz.com/blogs/index.xml", htmlUrl: "https://sandyuraz.com" },
  { name: "sylormiller.com", xmlUrl: "https://sylormiller.com/posts/index.xml", htmlUrl: "https://sylormiller.com" },
  { name: "onepercentrule.substack.com", xmlUrl: "https://onepercentrule.substack.com/feed", htmlUrl: "https://onepercentrule.substack.com" },
  { name: "adamdrake.com", xmlUrl: "https://adamdrake.com/blog/index.xml", htmlUrl: "https://adamdrake.com" },
  { name: "gwern.net", xmlUrl: "https://gwern.net/index.xml", htmlUrl: "https://gwern.net" },
  { name: "avi.im", xmlUrl: "https://avi.im/blag/index.xml", htmlUrl: "https://avi.im" },
  { name: "etbe.coker.com.au", xmlUrl: "https://etbe.coker.com.au/feed/", htmlUrl: "https://etbe.coker.com.au" },
  { name: "quuxplusone.github.io", xmlUrl: "https://quuxplusone.github.io/blog/feed.xml", htmlUrl: "https://quuxplusone.github.io" },
  { name: "tylercipriani.com", xmlUrl: "https://tylercipriani.com/blog/index.xml", htmlUrl: "https://tylercipriani.com" },
  { name: "spakhm.com", xmlUrl: "https://www.spakhm.com/feed.rss", htmlUrl: "https://spakhm.com" },
  { name: "scattered-thoughts.net", xmlUrl: "https://scattered-thoughts.net/rss.xml", htmlUrl: "https://scattered-thoughts.net" },
  { name: "zvzz.dev", xmlUrl: "https://zvzz.dev/index.xml", htmlUrl: "https://zvzz.dev" },
  { name: "momentsingraphics.de", xmlUrl: "https://momentsingraphics.de/rss.xml", htmlUrl: "https://momentsingraphics.de" },
  { name: "fzliu.github.io", xmlUrl: "https://fzliu.github.io/feed.xml", htmlUrl: "https://fzliu.github.io" },
  { name: "tomscii.sig7.se", xmlUrl: "https://tomscii.sig7.se/feed.xml", htmlUrl: "https://tomscii.sig7.se" },
  { name: "mbutz.github.io", xmlUrl: "https://mbutz.github.io/write/posts/index.xml", htmlUrl: "https://mbutz.github.io" },
  { name: "latent.space", xmlUrl: "https://www.latent.space/feed", htmlUrl: "https://latent.space" },

  { name: "Ludicity", xmlUrl: "https://ludic.mataroa.blog/rss/", htmlUrl: "https://ludic.mataroa.blog/" },
  { name: "Proper Fixation", xmlUrl: "https://yosefk.com/blog/feed", htmlUrl: "https://yosefk.com/blog" },
  { name: "云谦的博客", xmlUrl: "https://sorrycc.com/feed/", htmlUrl: "https://sorrycc.com/" },
  { name: "Hello my name is Niels Leenheer", xmlUrl: "https://nielsleenheer.com/feed/", htmlUrl: "https://nielsleenheer.com" },
  { name: "风痕 · 術&思", xmlUrl: "https://hughfenghen.github.io/rss.xml", htmlUrl: "https://hughfenghen.github.io/" },
  { name: "Total TypeScript", xmlUrl: "https://www.totaltypescript.com/rss.xml", htmlUrl: "https://www.totaltypescript.com/" },
  { name: "TW93 博客", xmlUrl: "https://tw93.fun/feed.xml", htmlUrl: "https://tw93.fun/" },
  { name: "pawelgrzybek.com", xmlUrl: "https://pawelgrzybek.com/feed.xml", htmlUrl: "https://pawelgrzybek.com/" },
  { name: "Engineer’s Codex", xmlUrl: "https://read.engineerscodex.com/feed", htmlUrl: "https://read.engineerscodex.com/" },
  { name: "Infrequently Noted", xmlUrl: "https://infrequently.org/feed/", htmlUrl: "https://infrequently.org/" },
  { name: "Owen的博客", xmlUrl: "https://www.owenyoung.com/atom.xml", htmlUrl: "https://www.owenyoung.com/" },
  { name: "Indigo's Digital Mirror", xmlUrl: "https://www.indigox.me/rss/", htmlUrl: "https://www.indigox.me/" },
  { name: "Hawstein's Blog", xmlUrl: "https://hawstein.com/feed.xml", htmlUrl: "https://hawstein.com/" },
  { name: "AddyOsmani.com", xmlUrl: "https://addyosmani.com/rss.xml", htmlUrl: "https://addyosmani.com/" },
  { name: "Viking Zhang, a front end developer", xmlUrl: "https://vikingz.me/rss.xml", htmlUrl: "https://vikingz.me/" },
  { name: "Josh Comeau's blog", xmlUrl: "https://www.joshwcomeau.com/rss.xml", htmlUrl: "https://www.joshwcomeau.com" },
  { name: "阮一峰的网络日志", xmlUrl: "https://www.ruanyifeng.com/blog/atom.xml", htmlUrl: "https://www.ruanyifeng.com/blog/" },
  { name: "SpeedCurve Blog", xmlUrl: "https://www.speedcurve.com/blog/rss/", htmlUrl: "https://www.speedcurve.com/blog/" },
  { name: "Martin Fowler", xmlUrl: "https://martinfowler.com/feed.atom", htmlUrl: "https://martinfowler.com/" },
  { name: "The Pragmatic Engineer", xmlUrl: "https://blog.pragmaticengineer.com/rss/", htmlUrl: "https://blog.pragmaticengineer.com/" },
  { name: "Bram.us", xmlUrl: "https://www.bram.us/feed/", htmlUrl: "https://www.bram.us/" },
  { name: "构建我的被动收入", xmlUrl: "https://www.bmpi.dev/index.xml", htmlUrl: "https://www.bmpi.dev" },
  { name: "Anthony Fu", xmlUrl: "https://antfu.me/feed.xml", htmlUrl: "https://antfu.me/" },
  { name: "2ality – JavaScript and more", xmlUrl: "https://2ality.com/feeds/posts.atom", htmlUrl: "https://2ality.com/" },
  { name: "404 [[ ]] KIDS SEE GHOSTS", xmlUrl: "https://kidsseeghosts.substack.com/feed", htmlUrl: "https://kidsseeghosts.substack.com/" },
  { name: "小胡子哥的个人网站", xmlUrl: "https://www.barretlee.com/rss2.xml?code=989a6aaf710a7bfc999d95249d24a1ef", htmlUrl: "https://www.barretlee.com/" },
  { name: "Trevor-Indrek Lasn | Principal Software Engineer & Entrepreneur", xmlUrl: "https://www.trevorlasn.com/rss.xml", htmlUrl: "https://trevorlasn.com/" },
  { name: "ugur", xmlUrl: "https://www.rugu.dev/en/index.xml", htmlUrl: "https://rugu.dev/en/" },
  { name: "chaofa用代码打点酱油", xmlUrl: "https://yuanchaofa.com/rss.xml", htmlUrl: "https://yuanchaofa.com/" },
  { name: "Elevate", xmlUrl: "https://addyo.substack.com/feed", htmlUrl: "https://addyo.substack.com/" },
];

export const CATEGORIES = {
  'AI_ML': { emoji: '🤖', name: 'AI / ML', desc: 'AI、机器学习、LLM、深度学习' },
  'SECURITY': { emoji: '🔒', name: '安全', desc: '安全、隐私、漏洞、加密' },
  'ENGINEERING': { emoji: '⚙️', name: '工程', desc: '软件工程、架构、编程语言、系统设计' },
  'TOOLS_OPENSOURCE': { emoji: '🛠', name: '工具 / 开源', desc: '开发工具、开源项目、新发布的库/框架' },
  'OPINION': { emoji: '💡', name: '观点 / 杂谈', desc: '行业观点、个人思考、职业发展' },
  'OTHER': { emoji: '📝', name: '其他', desc: '不属于以上分类的内容' }
};
